server {
    listen 80;
    server_name elitenursepartners.com.au www.elitenursepartners.com.au;

    location ^~ /.well-known/acme-challenge/ {
        root /opt/enp/dist/public/enp-review-28aug26;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name elitenursepartners.com.au www.elitenursepartners.com.au;

    root /opt/enp/dist/public/enp-review-28aug26;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/elitenursepartners.com.au/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/elitenursepartners.com.au/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location / {
        try_files $uri $uri/ =404;
    }
}
