// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rbac-matrix/RBACMatrix.tsx": () => import("../components/mockups/rbac-matrix/RBACMatrix.tsx")
};
